#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "spotibad.h"

int main(){
  srand(time(NULL)); // prng MUST be seeded here, and nowhere else

  printf("  ___ ___  ___ _____ ___ ___   _   ___  \n");
  printf(" / __| _ \\/ _ \\_   _|_ _| _ ) /_\\ |   \\ \n");
  printf(" \\__ \\  _/ (_) || |  | || _ \\/ _ \\| |) |\n");
  printf(" |___/_|  \\___/ |_| |___|___/_/ \\_\\___/ \n");
  printf("                                        \n");
  printf(" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \n");

  printf("Let's add some songs.\n");
  add_song_node(make_song_node("Maybe"                                               ,"Enrique Iglesias"));
  add_song_node(make_song_node("Troublesome Waters"                                  ,"Johnny Cash"));
  add_song_node(make_song_node("I Wanna Be Your Lover"                               ,"La Bionda"));
  add_song_node(make_song_node("Welcome To The Jungle"                               ,"Guns N' Roses"));
  add_song_node(make_song_node("Lose Yourself"                                       ,"Eminem"));
  add_song_node(make_song_node("All Rise"                                            ,"Wovenwar"));
  add_song_node(make_song_node("Things I Didn't Say"                                 ,"Adam Lambert"));
  add_song_node(make_song_node("Wheel of Fortune"                                    ,"Ace of Base"));
  add_song_node(make_song_node("If I'm"                                              ,"Sea Oleena"));
  add_song_node(make_song_node("My Songs Know What You Did In The Dark"              ,"Fall Out Boy"));
  add_song_node(make_song_node("Steppin' out with My Baby"                           ,"Tony Bennett"));
  add_song_node(make_song_node("Paradise by the Dashboard Light"                     ,"Meat Loaf"));
  add_song_node(make_song_node("Hymn For The Weekend"                                ,"Coldplay"));
  add_song_node(make_song_node("We Will Rock You"                                    ,"Queen"));
  add_song_node(make_song_node("Let Love Hold You Now"                               ,"Jamie Lawson"));
  add_song_node(make_song_node("We Didn't Start the Fire"                            ,"Billy Joel"));
  add_song_node(make_song_node("Best Mistake"                                        ,"Ariana Grande"));
  add_song_node(make_song_node("Say Something"                                       ,"A Great Big World"));
  add_song_node(make_song_node("Mammas, Don't Let Your Babies Grow Up to Be Cowboys" ,"Waylon Jennings"));
  add_song_node(make_song_node("Rock Of The Bells"                                   ,"Matthew Rodgers"));
  add_song_node(make_song_node("Underdog"                                            ,"Imagine Dragons"));
  add_song_node(make_song_node("Really Don't Care"                                   ,"Demi Lovato"));
  add_song_node(make_song_node("Sandy in the Rain"                                   ,"The Lost American JazzBook"));
  add_song_node(make_song_node("Love Me Harder"                                      ,"Ariana Grande"));
  add_song_node(make_song_node("Bohemian Rhapsody"                                   ,"Queen"));
  add_song_node(make_song_node("Together Forever"                                    ,"Rick Astley"));
  add_song_node(make_song_node("A Guy Walks into a Bar"                              ,"Tyler Farr"));
  add_song_node(make_song_node("One Man Can Change The World"                        ,"Big Sean"));
  add_song_node(make_song_node("Slammin' Mannequin"                                  ,"Starchild & The New Romantic"));
  add_song_node(make_song_node("You Spin Me Round"                                   ,"Jessica Simpson"));
  add_song_node(make_song_node("Dreamer"                                             ,"Europe"));
  add_song_node(make_song_node("Georgy Porgy"                                        ,"Toto"));
  add_song_node(make_song_node("Nostalgic"                                           ,"Kelly Clarkson"));
  add_song_node(make_song_node("Rock and Roll, Hoochie Koo"                          ,"Rick Derringer"));
  add_song_node(make_song_node("Eugene Onegin, Act III: \"Polonaise\""               ,"Leonard Slatkin"));
  add_song_node(make_song_node("Me & The Rhythm"                                     ,"Selena Gomez"));
  add_song_node(make_song_node("Calico"                                              ,"Widowspeak"));
  add_song_node(make_song_node("Lay Me Down In Dixie"                                ,"Johnny Cash"));
  add_song_node(make_song_node("Without the Love"                                    ,"Demi Lovato"));
  add_song_node(make_song_node("Down Home Boys"                                      ,"Cole Swindell"));
  add_song_node(make_song_node("The Violet Hour"                                     ,"The Civil Wars"));
  add_song_node(make_song_node("She's Not You"                                       ,"Elvis Presley"));
  add_song_node(make_song_node("Eye of the Needle"                                   ,"Sia"));
  add_song_node(make_song_node("Remember That"                                       ,"Jessica Simpson"));
  add_song_node(make_song_node("Dragonfly"                                           ,"Johnny Star"));
  add_song_node(make_song_node("Pamela"                                              ,"Toto"));
  add_song_node(make_song_node("Ordinary"                                            ,"The Alpine Treeline"));
  add_song_node(make_song_node("Shine On You Crazy Diamond"                          ,"Pink Floyd"));
  add_song_node(make_song_node("Any Way You Want It"                                 ,"Journey"));
  add_song_node(make_song_node("Camouflage"                                          ,"Selena Gomez"));
  add_song_node(make_song_node("Pushing Me Away"                                     ,"Linkin Park"));
  add_song_node(make_song_node("Never Been Hurt"                                     ,"Demi Lovato"));
  add_song_node(make_song_node("Nocturnes, Op. 9: No. 1 in B-Flat Minor"             ,"Arthur Rubinstein"));
  add_song_node(make_song_node("Sharp Dressed Man"                                   ,"ZZ Top"));
  add_song_node(make_song_node("This Is How We Do"                                   ,"Katy Perry"));
  add_song_node(make_song_node("International Smile"                                 ,"Katy Perry"));
  add_song_node(make_song_node("Adagio for Strings from the String Quartet, Op. 11"  ,"Leonard Bernstein"));
  add_song_node(make_song_node("Symphony No. 7 in A Major, Op. 92: II. Allegretto"   ,"Leonard Bernstein"));
  add_song_node(make_song_node("Hold the Line"                                       ,"Toto"));
  add_song_node(make_song_node("Resist and Bite"                                     ,"Sabaton"));
  add_song_node(make_song_node("Lotto"                                               ,"Charlie Wilson"));
  add_song_node(make_song_node("Royal Garden Blues"                                  ,"Count Basie & His All American Rhythm Section"));
  add_song_node(make_song_node("Neon Lights"                                         ,"Demi Lovato"));
  add_song_node(make_song_node("The Veldt"                                           ,"deadmau5"));
  add_song_node(make_song_node("Return to Sender"                                    ,"Elvis Presley"));
  add_song_node(make_song_node("Escape"                                              ,"Enrique Iglesias"));
  add_song_node(make_song_node("Good Luck Charm"                                     ,"Elvis Presley"));
  add_song_node(make_song_node("So Near, So Far"                                     ,"Miles Davis"));
  add_song_node(make_song_node("Good Goes The Bye"                                   ,"Kelly Clarkson"));
  add_song_node(make_song_node("My Sweet Summer"                                     ,"Dirty Heads"));
  add_song_node(make_song_node("Shouldn't Come Back"                                 ,"Demi Lovato"));
  add_song_node(make_song_node("Till the World Ends"                                 ,"Britney Spears"));
  add_song_node(make_song_node("Can't Fight This Feeling"                            ,"REO Speedwagon"));
  add_song_node(make_song_node("Fire Starter"                                        ,"Demi Lovato"));
  add_song_node(make_song_node("Rock And Roll Dreams Come Through"                   ,"Meat Loaf"));
  add_song_node(make_song_node("Beaten in Lips"                                      ,"Beartooth"));
  add_song_node(make_song_node("I Knew You Were Trouble"                             ,"Taylor Swift"));
  add_song_node(make_song_node("Concerto No. 21 in C Major, K. 467: Andante"         ,"Alicia De Larrocha"));
  add_song_node(make_song_node("Girl with the Red Balloon"                           ,"The Civil Wars"));
  add_song_node(make_song_node("Be With You"                                         ,"Enrique Iglesias"));
  add_song_node(make_song_node("Shine on Harvest Moon"                               ,"Count Basie, His Instrumentalists & His Rhythm"));
  add_song_node(make_song_node("Layla"                                               ,"Derek & The Dominos"));
  add_song_node(make_song_node("We Are Young"                                        ,"Fun."));
  add_song_node(make_song_node("Raspberry Beret"                                     ,"Prince & The Revolution"));
  add_song_node(make_song_node("Something That We're Not"                            ,"Demi Lovato"));
  add_song_node(make_song_node("Overdose"                                            ,"Little Daylight"));
  add_song_node(make_song_node("Hop up My Ladies"                                    ,"Elizabeth Mitchell"));
  add_song_node(make_song_node("Hotel California"                                    ,"Eagles"));
  add_song_node(make_song_node("The Final Countdown"                                 ,"Europe"));
  add_song_node(make_song_node("No Way Out"                                          ,"Bullet For My Valentine"));
  add_song_node(make_song_node("Love Story"                                          ,"Taylor Swift"));
  add_song_node(make_song_node("Clarinet Concerto in A Major, K. 622: Adagio"        ,"Richard Stoltzman"));
  add_song_node(make_song_node("There Might Be Coffee"                               ,"deadmau5"));
  add_song_node(make_song_node("Szymanowski"                                         ,"Volodja Balzalorsky"));
  add_song_node(make_song_node("These Boots Are Made for Walkin'"                    ,"Jessica Simpson"));
  add_song_node(make_song_node("You Want a Battle?"                                  ,"Bullet For My Valentine"));
  add_song_node(make_song_node("City That You Love"                                  ,"Aaron R. Smith"));
  add_song_node(make_song_node("No More Mr. Nice Guy"                                ,"Alice Cooper"));
  add_song_node(make_song_node("Yellow Ticket"                                       ,"Matthew Rodgers"));
  add_song_node(make_song_node("Symphony No. 40 in G Minor, K. 550: Molto Allegro"   ,"James Levine"));
  add_song_node(make_song_node("Who Needs Pictures"                                  ,"Brad Paisley"));
  add_song_node(make_song_node("When You Were Mine"                                  ,"Cyndi Lauper"));
  add_song_node(make_song_node("Underneath the Tree"                                 ,"Kelly Clarkson"));
  add_song_node(make_song_node("Survivors"                                           ,"Selena Gomez"));
  add_song_node(make_song_node("Poison"                                              ,"Alice Cooper"));
  add_song_node(make_song_node("Red Lights"                                          ,"Tiësto"));
  add_song_node(make_song_node("Pure Imagination"                                    ,"Josh Groban"));
  add_song_node(make_song_node("Dance The Night Away"                                ,"David Banner"));
  add_song_node(make_song_node("Holding Out For A Hero"                              ,"Ella Mae Bowen"));
  add_song_node(make_song_node("Can't Get Away from a Good Time"                     ,"Logan Mize"));
  add_song_node(make_song_node("We Never Said Goodbye"                               ,"Dionne Warwick"));
  add_song_node(make_song_node("4 Carats"                                            ,"Kelly Clarkson"));
  add_song_node(make_song_node("The Entertainer"                                     ,"Dick Hyman"));
  add_song_node(make_song_node("Hold It Against Me"                                  ,"Britney Spears"));
  add_song_node(make_song_node("Deja Vu"                                             ,"Dionne Warwick"));
  add_song_node(make_song_node("Crying In the Chapel"                                ,"Elvis Presley"));
  add_song_node(make_song_node("Bleeding Out"                                        ,"Imagine Dragons"));
  add_song_node(make_song_node("You Are My Sunshine"                                 ,"Norman Blake"));
  add_song_node(make_song_node("Hey Now"                                             ,"Cyndi Lauper"));
  add_song_node(make_song_node("Oogie Boogie's Song"                                 ,"Ken Page"));
  add_song_node(make_song_node("Far Side Banks of Jordan"                            ,"Johnny Cash"));
  add_song_node(make_song_node("Peer Gynt, Op. 23: Morning Mood"                     ,"Esa-Pekka Salonen"));
  add_song_node(make_song_node("When I Was Your Man"                                 ,"Bruno Mars"));
  add_song_node(make_song_node("Umbrella"                                            ,"Jean Rohe"));
  add_song_node(make_song_node("I'm Not Sorry"                                       ,"Celeste Buckingham"));
  add_song_node(make_song_node("Black Crow"                                          ,"Blackbird And The Storm"));
  add_song_node(make_song_node("Beyond the Veil"                                     ,"Lindsey Stirling"));
  add_song_node(make_song_node("Cherry Bomb"                                         ,"The Runaways"));
  add_song_node(make_song_node("Like A Boy"                                          ,"Ciara"));
  add_song_node(make_song_node("You're Still a Mystery"                              ,"Bleachers"));
  add_song_node(make_song_node("Crying in the Chapel"                                ,"Elvis Presley"));
  add_song_node(make_song_node("Imagine"                                             ,"John Lennon"));
  add_song_node(make_song_node("Down Home Country Blues"                             ,"Bradley West"));
  add_song_node(make_song_node("Superstition"                                        ,"Stevie Wonder"));
  add_song_node(make_song_node("The sound of silence"                                ,"Paul Simon and Art Garfunkel"));
  add_song_node(make_song_node("Tom's Diner"                                         ,"Suzanne Vega"));
  add_song_node(make_song_node("September"                                           ,"Earth, Wind & Fire"));
  add_song_node(make_song_node("Radioactive"                                         ,"Imagine Dragons"));
  add_song_node(make_song_node("Hallelujah"                                          ,"Jeff Buckley"));
  add_song_node(make_song_node("Thank You"                                           ,"Sly & The Family Stone"));
  add_song_node(make_song_node("Something About December"                            ,"Christina Perri"));
  add_song_node(make_song_node("Teenage Dream"                                       ,"Katy Perry"));
  add_song_node(make_song_node("The Hills"                                           ,"The Weeknd"));
  add_song_node(make_song_node("Ain't No Mountain High Enough"                       ,"Marvin Gaye"));
  add_song_node(make_song_node("Kommander's Car"                                     ,"Katy Carr"));
  add_song_node(make_song_node("This Is Halloween"                                   ,"Marilyn Manson"));
  add_song_node(make_song_node("In The Jailhouse Now"                                ,"Harley Allen"));
  add_song_node(make_song_node("Let Your Tears Fall"                                 ,"Kelly Clarkson"));
  add_song_node(make_song_node("No More Guns"                                        ,"Mr Benn"));
  add_song_node(make_song_node("Legendary Lovers"                                    ,"Katy Perry"));
  add_song_node(make_song_node("I Understand"                                        ,"Sophie Koh"));
  add_song_node(make_song_node("Raised by a Good Time"                               ,"Steven Lee Olsen"));
  add_song_node(make_song_node("We like to Party"                                    ,"Vengaboys"));
  add_song_node(make_song_node("Push It"                                             ,"Salt-N-Pepa"));
  add_song_node(make_song_node("Total Eclipse of the Heart"                          ,"Bonnie Tyler"));
  add_song_node(make_song_node("Loin d'ici"                                          ,"ZoË"));
  add_song_node(make_song_node("Fortunate Son"                                       ,"Creedence Clearwater Revival"));
  add_song_node(make_song_node("Can't Help Falling In Love"                          ,"Elvis Presley"));
  add_song_node(make_song_node("Ghost Town"                                          ,"Adam Lambert"));
  add_song_node(make_song_node("Mississippi Queen"                                   ,"Mountain"));
  add_song_node(make_song_node("Gimme Sympathy"                                      ,"Metric"));
  add_song_node(make_song_node("Stan"                                                ,"Eminem"));
  add_song_node(make_song_node("Come Together"                                       ,"Echosmith"));
  add_song_node(make_song_node("Like A Rose"                                         ,"Ashley Monroe"));
  add_song_node(make_song_node("Rock the Night"                                      ,"Europe"));
  add_song_node(make_song_node("(Don't Fear) The Reaper"                             ,"Blue Oyster Cult"));
  add_song_node(make_song_node("Crimson Wave"                                        ,"Tacocat"));
  add_song_node(make_song_node("I Don't Want To Lose Her"                            ,"Rick Astley"));
  add_song_node(make_song_node("Wonderful Things"                                    ,"Ryan Corn"));
  add_song_node(make_song_node("Raining Sunshine"                                    ,"Miranda Cosgrove"));
  add_song_node(make_song_node("Raindrops Keep Falling on My Head"                   ,"B.J. Thomas"));
  add_song_node(make_song_node("True Colors"                                         ,"Cyndi Lauper"));
  add_song_node(make_song_node("Santa's Got A Choo Choo Train"                       ,"Blake Shelton"));
  add_song_node(make_song_node("Hope You Get Lonely Tonight"                         ,"Cole Swindell"));
  add_song_node(make_song_node("Summertime"                                          ,"Miles Davis"));
  add_song_node(make_song_node("Fall"                                                ,"Miles Davis"));
  add_song_node(make_song_node("Cactus In the Valley"                                ,"Lights"));
  add_song_node(make_song_node("Never Gonna Give You Up"                             ,"Rick Astley"));
  add_song_node(make_song_node("I Can't Make You Love Me"                            ,"Bonnie Raitt"));
  add_song_node(make_song_node("Blue"                                                ,"Dance Fever"));
  add_song_node(make_song_node("Whip It"                                             ,"Devo"));
  add_song_node(make_song_node("Please Mr. Kennedy"                                  ,"Justin Timberlake"));
  add_song_node(make_song_node("Rockstar"                                            ,"A Great Big World"));
  add_song_node(make_song_node("Big Rock Candy Mountain"                             ,"Harry McClintock"));
  add_song_node(make_song_node("Roar"                                                ,"Katy Perry"));
  add_song_node(make_song_node("Luka"                                                ,"Suzanne Vega"));
  add_song_node(make_song_node("Do Lightbikes Run On Lightfuel?"                     ,"Josh Zimmerman"));
  add_song_node(make_song_node("Africa"                                              ,"Toto"));
  add_song_node(make_song_node("Demons"                                              ,"Imagine Dragons"));
  add_song_node(make_song_node("Stacy's Mom"                                         ,"Fountains Of Wayne"));
  add_song_node(make_song_node("Flare Gun"                                           ,"In Tall Buildings"));
  add_song_node(make_song_node("Go"                                                  ,"The Chemical Brothers"));
  add_song_node(make_song_node("Escape (The Piña Colada Song)"                       ,"Rupert Holmes"));
  add_song_node(make_song_node("One More Time"                                       ,"Daft Punk"));
  add_song_node(make_song_node("See You Again (feat. Charlie Puth)"                  ,"Wiz Khalifa"));
  add_song_node(make_song_node("Tip Of My Tongue"                                    ,"The Civil Wars"));
  add_song_node(make_song_node("Without Me"                                          ,"Eminem"));
  add_song_node(make_song_node("Time After Time"                                     ,"Cyndi Lauper"));
  add_song_node(make_song_node("Stronger (Explicit)"                                 ,"Kanye West"));
  add_song_node(make_song_node("Scarborough Fair / Canticle"                         ,"Simon & Garfunkel"));
  add_song_node(make_song_node("Piano Man"                                           ,"Billy Joel"));
  add_song_node(make_song_node("sweet home alabama"                                  ,"lynyrd skynyrd"));
  add_song_node(make_song_node("Do You Believe In Magic"                             ,"The Lovin' Spoonful"));

  printf("\n\n\n\n\nTake a look at all these songs!\n");
  print_library();

  printf("\n\n\n\n\nGreat, let's search for some songs.\n");
  printf("Good: %p\n", song_search("Whip It", "Devo"));
  printf("Good: %p\n", song_search("Santa's Got A Choo Choo Train", "Blake Shelton"));
  printf("Bad:  %p\n", song_search("not a title", "not an artist"));

  printf("\n\n\n\n\nHow about some artists?\n");
  printf("Good: %p\n", artist_search("Jeff Buckley"));
  printf("Good: %p\n", artist_search("Pink Floyd"));
  printf("Bad:  %p\n", artist_search("not an artist"));

  printf("\n\n\n\n\nGive me all the artists beginning with 'P'!\n");
  print_letter('P');

  printf("\n\n\n\n\nBut wait, does it work for 'p'?\n");
  print_letter('p');

  printf("\n\n\n\n\nAll the songs by a specific artist?\n");
  print_artists_songs("Rick Astley");
  print_artists_songs("Selena Gomez");
  print_artists_songs("not an artist");

  printf("\n\n\n\n\nPlay me 10 random songs.\n");
  shuffle(10);

  printf("\n\n\n\n\nLet's delete a few songs.\n");
  delete_song(song_search("One Man Can Change The World"                       ,"Big Sean"));
  delete_song(song_search("Slammin' Mannequin"                                 ,"Starchild & The New Romantic"));
  delete_song(song_search("You Spin Me Round"                                  ,"Jessica Simpson"));
  delete_song(song_search("Dreamer"                                            ,"Europe"));
  delete_song(song_search("Georgy Porgy"                                       ,"Toto"));
  delete_song(song_search("Nostalgic"                                          ,"Kelly Clarkson"));
  delete_song(song_search("Rock and Roll, Hoochie Koo"                         ,"Rick Derringer"));
  delete_song(song_search("Eugene Onegin, Act III: \"Polonaise\""              ,"Leonard Slatkin"));
  delete_song(song_search("Me & The Rhythm"                                    ,"Selena Gomez"));
  delete_song(song_search("Calico"                                             ,"Widowspeak"));
  delete_song(song_search("Lay Me Down In Dixie"                               ,"Johnny Cash"));
  delete_song(song_search("Without the Love"                                   ,"Demi Lovato"));
  delete_song(song_search("Down Home Boys"                                     ,"Cole Swindell"));
  delete_song(song_search("The Violet Hour"                                    ,"The Civil Wars"));
  delete_song(song_search("She's Not You"                                      ,"Elvis Presley"));
  delete_song(song_search("Eye of the Needle"                                  ,"Sia"));
  delete_song(song_search("Remember That"                                      ,"Jessica Simpson"));
  delete_song(song_search("Dragonfly"                                          ,"Johnny Star"));
  delete_song(song_search("Pamela"                                             ,"Toto"));
  delete_song(song_search("Ordinary"                                           ,"The Alpine Treeline"));
  delete_song(song_search("Shine On You Crazy Diamond"                         ,"Pink Floyd"));
  delete_song(song_search("Any Way You Want It"                                ,"Journey"));
  delete_song(song_search("Camouflage"                                         ,"Selena Gomez"));
  delete_song(song_search("Pushing Me Away"                                    ,"Linkin Park"));
  delete_song(song_search("Never Been Hurt"                                    ,"Demi Lovato"));
  delete_song(song_search("Nocturnes, Op. 9: No. 1 in B-Flat Minor"            ,"Arthur Rubinstein"));
  delete_song(song_search("Sharp Dressed Man"                                  ,"ZZ Top"));
  delete_song(song_search("This Is How We Do"                                  ,"Katy Perry"));
  delete_song(song_search("International Smile"                                ,"Katy Perry"));
  delete_song(song_search("Adagio for Strings from the String Quartet, Op. 11" ,"Leonard Bernstein"));
  delete_song(song_search("Symphony No. 7 in A Major, Op. 92: II. Allegretto"  ,"Leonard Bernstein"));
  delete_song(song_search("Hold the Line"                                      ,"Toto"));
  delete_song(song_search("Resist and Bite"                                    ,"Sabaton"));
  delete_song(song_search("Lotto"                                              ,"Charlie Wilson"));
  delete_song(song_search("Royal Garden Blues"                                 ,"Count Basie & His All American Rhythm Section"));
  delete_song(song_search("Neon Lights"                                        ,"Demi Lovato"));
  delete_song(song_search("The Veldt"                                          ,"deadmau5"));
  delete_song(song_search("Return to Sender"                                   ,"Elvis Presley"));
  delete_song(song_search("Escape"                                             ,"Enrique Iglesias"));
  delete_song(song_search("Good Luck Charm"                                    ,"Elvis Presley"));
  delete_song(song_search("So Near, So Far"                                    ,"Miles Davis"));
  delete_song(song_search("Good Goes The Bye"                                  ,"Kelly Clarkson"));
  delete_song(song_search("My Sweet Summer"                                    ,"Dirty Heads"));
  delete_song(song_search("Shouldn't Come Back"                                ,"Demi Lovato"));
  delete_song(song_search("Till the World Ends"                                ,"Britney Spears"));
  delete_song(song_search("Can't Fight This Feeling"                           ,"REO Speedwagon"));
  delete_song(song_search("Fire Starter"                                       ,"Demi Lovato"));
  delete_song(song_search("Rock And Roll Dreams Come Through"                  ,"Meat Loaf"));
  delete_song(song_search("Beaten in Lips"                                     ,"Beartooth"));
  delete_song(song_search("I Knew You Were Trouble"                            ,"Taylor Swift"));
  delete_song(song_search("Concerto No. 21 in C Major, K. 467: Andante"        ,"Alicia De Larrocha"));
  delete_song(song_search("Girl with the Red Balloon"                          ,"The Civil Wars"));
  delete_song(song_search("Be With You"                                        ,"Enrique Iglesias"));
  delete_song(song_search("Shine on Harvest Moon"                              ,"Count Basie, His Instrumentalists & His Rhythm"));
  delete_song(song_search("Layla"                                              ,"Derek & The Dominos"));
  delete_song(song_search("We Are Young"                                       ,"Fun."));
  delete_song(song_search("Raspberry Beret"                                    ,"Prince & The Revolution"));
  delete_song(song_search("Something That We're Not"                           ,"Demi Lovato"));
  delete_song(song_search("Overdose"                                           ,"Little Daylight"));
  delete_song(song_search("Hop up My Ladies"                                   ,"Elizabeth Mitchell"));
  delete_song(song_search("Hotel California"                                   ,"Eagles"));
  delete_song(song_search("The Final Countdown"                                ,"Europe"));
  delete_song(song_search("No Way Out"                                         ,"Bullet For My Valentine"));
  delete_song(song_search("Love Story"                                         ,"Taylor Swift"));
  delete_song(song_search("Clarinet Concerto in A Major, K. 622: Adagio"       ,"Richard Stoltzman"));
  delete_song(song_search("There Might Be Coffee"                              ,"deadmau5"));
  delete_song(song_search("Szymanowski"                                        ,"Volodja Balzalorsky"));
  delete_song(song_search("These Boots Are Made for Walkin'"                   ,"Jessica Simpson"));
  delete_song(song_search("You Want a Battle?"                                 ,"Bullet For My Valentine"));
  delete_song(song_search("City That You Love"                                 ,"Aaron R. Smith"));
  delete_song(song_search("No More Mr. Nice Guy"                               ,"Alice Cooper"));
  delete_song(song_search("Yellow Ticket"                                      ,"Matthew Rodgers"));
  delete_song(song_search("Symphony No. 40 in G Minor, K. 550: Molto Allegro"  ,"James Levine"));
  delete_song(song_search("Who Needs Pictures"                                 ,"Brad Paisley"));
  delete_song(song_search("When You Were Mine"                                 ,"Cyndi Lauper"));
  delete_song(song_search("Underneath the Tree"                                ,"Kelly Clarkson"));
  delete_song(song_search("Survivors"                                          ,"Selena Gomez"));
  delete_song(song_search("Poison"                                             ,"Alice Cooper"));
  delete_song(song_search("Red Lights"                                         ,"Tiësto"));
  delete_song(song_search("Pure Imagination"                                   ,"Josh Groban"));
  delete_song(song_search("Dance The Night Away"                               ,"David Banner"));
  delete_song(song_search("Holding Out For A Hero"                             ,"Ella Mae Bowen"));
  delete_song(song_search("Can't Get Away from a Good Time"                    ,"Logan Mize"));
  delete_song(song_search("We Never Said Goodbye"                              ,"Dionne Warwick"));
  delete_song(song_search("4 Carats"                                           ,"Kelly Clarkson"));
  delete_song(song_search("The Entertainer"                                    ,"Dick Hyman"));
  delete_song(song_search("Hold It Against Me"                                 ,"Britney Spears"));
  delete_song(song_search("Deja Vu"                                            ,"Dionne Warwick"));
  delete_song(song_search("Crying In the Chapel"                               ,"Elvis Presley"));
  delete_song(song_search("Bleeding Out"                                       ,"Imagine Dragons"));
  delete_song(song_search("You Are My Sunshine"                                ,"Norman Blake"));
  delete_song(song_search("Hey Now"                                            ,"Cyndi Lauper"));
  delete_song(song_search("Oogie Boogie's Song"                                ,"Ken Page"));
  delete_song(song_search("Far Side Banks of Jordan"                           ,"Johnny Cash"));
  delete_song(song_search("Peer Gynt, Op. 23: Morning Mood"                    ,"Esa-Pekka Salonen"));
  delete_song(song_search("When I Was Your Man"                                ,"Bruno Mars"));
  delete_song(song_search("Umbrella"                                           ,"Jean Rohe"));
  delete_song(song_search("I'm Not Sorry"                                      ,"Celeste Buckingham"));
  delete_song(song_search("Black Crow"                                         ,"Blackbird And The Storm"));
  delete_song(song_search("Beyond the Veil"                                    ,"Lindsey Stirling"));
  delete_song(song_search("Cherry Bomb"                                        ,"The Runaways"));
  delete_song(song_search("Like A Boy"                                         ,"Ciara"));
  delete_song(song_search("You're Still a Mystery"                             ,"Bleachers"));
  delete_song(song_search("Crying in the Chapel"                               ,"Elvis Presley"));
  delete_song(song_search("Imagine"                                            ,"John Lennon"));
  delete_song(song_search("Down Home Country Blues"                            ,"Bradley West"));
  delete_song(song_search("Superstition"                                       ,"Stevie Wonder"));
  delete_song(song_search("The sound of silence"                               ,"Paul Simon and Art Garfunkel"));
  delete_song(song_search("Tom's Diner"                                        ,"Suzanne Vega"));

  printf("\n\n\n\n\nThat was fun. Goodbye!\n");
  clear_all();
}

